import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ProfileStore } from '../state/profile.store';
import { AuthStore } from '../state/auth.store';
import { Role, User } from '../core/models';

@Component({ selector: 'jhub-profile-page', standalone: true, imports: [ReactiveFormsModule, RouterLink], changeDetection: ChangeDetectionStrategy.OnPush, template: `
  <main class="profile-page page-width"><div class="profile-heading"><div><p class="eyebrow">INNOVATOR PROFILE</p><h1>Your bio-data, <em>your story.</em></h1><p>Keep your information current so project and loan records stay accountable.</p></div><a class="arrow-link" routerLink="/app/settings">Settings ↗</a></div>@if (profile.success()) {<div class="notice success" role="status">{{ profile.success() }}</div>}@if (profile.error()) {<div class="notice error" role="alert">{{ profile.error() }}</div>}<section class="profile-layout"><div class="avatar-card"><div class="avatar">{{ initials() }}</div><h2>{{ form.controls.fullName.value || 'Your name' }}</h2><p>{{ form.controls.email.value }}</p><label class="upload-button">Change profile picture<input type="file" accept="image/*" (change)="upload($event)"></label><small>JPG or PNG · max 5MB</small></div><form class="profile-form" [formGroup]="form" (ngSubmit)="save()"><div class="form-grid"><label>Full name<input formControlName="fullName">@if (invalid('fullName')) {<small>Full name is required.</small>}</label><label>Official email<input type="email" formControlName="email">@if (invalid('email')) {<small>Enter a valid email.</small>}</label><label>Phone number<input formControlName="phoneNumber">@if (invalid('phoneNumber')) {<small>Enter a valid phone number.</small>}</label><label>Identification / student number<input formControlName="identificationId"></label><label>Department / track<input formControlName="department"></label><label>Primary role<input formControlName="primaryRole"></label></div><label>Bio / skill summary<textarea rows="5" formControlName="bio" placeholder="Tell the JHUB community what you are working on."></textarea></label><label>GitHub / portfolio URL<input type="url" formControlName="githubUrl" placeholder="https://"></label><div class="form-actions"><button type="button" class="secondary-button" (click)="cancel()">Cancel</button><button type="submit" class="primary-button" [disabled]="profile.saving()">{{ profile.saving() ? 'Saving…' : 'Save profile' }} <span>→</span></button></div></form></section></main>
`, styles: [`:host{display:block}.profile-page{padding:65px 0 110px}.profile-heading{display:flex;justify-content:space-between;align-items:end;margin-bottom:35px}.eyebrow{color:#3ea945;font-size:10px;font-weight:800;letter-spacing:2px;margin:0 0 18px}.profile-heading h1{font:400 clamp(40px,5vw,58px)/1.05 Georgia,serif;color:#262571;margin:0}.profile-heading h1 em{color:#3ea945}.profile-heading p:last-child{color:#667083;font-size:13px}.arrow-link{color:#262571;text-decoration:none;font-size:12px;font-weight:700}.profile-layout{display:grid;grid-template-columns:270px 1fr;gap:20px;align-items:start}.avatar-card,.profile-form{background:#fff;border:1px solid #e6e8ee;padding:28px}.avatar-card{text-align:center}.avatar{width:100px;height:100px;display:grid;place-items:center;margin:5px auto 18px;background:#e5eafa;color:#262571;font:38px Georgia,serif}.avatar-card h2{font:24px Georgia,serif;color:#262571;margin:0}.avatar-card p{font-size:11px;color:#7c8492}.upload-button{display:block;border:1px solid #dce0e8;padding:11px 8px;color:#262571;font-size:11px;font-weight:700;margin-top:22px}.upload-button input{display:none}.avatar-card small{display:block;color:#9aa1ad;font-size:9px;margin-top:10px}.profile-form{display:grid;gap:18px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.profile-form label{display:block;color:#586174;font-size:11px}.profile-form input,.profile-form textarea{display:block;width:100%;border:1px solid #dce0e8;margin-top:7px;padding:12px;outline-color:#3ea945;resize:vertical}.profile-form small{display:block;color:#e6292a;margin-top:5px;font-size:10px}.form-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:8px}.notice{padding:12px 15px;margin-bottom:16px;font-size:12px;background:#fff}.notice.success{border-left:3px solid #3ea945;color:#26742b}.notice.error{border-left:3px solid #e6292a;color:#a51f20}@media(max-width:760px){.profile-page{padding-top:45px}.profile-heading{display:block}.profile-heading .arrow-link{display:inline-block;margin-top:18px}.profile-layout{grid-template-columns:1fr}.form-grid{grid-template-columns:1fr}.form-actions{justify-content:stretch}.form-actions button{flex:1;justify-content:center}}`]
})
export class ProfilePageComponent {
  protected readonly profile = inject(ProfileStore); private readonly auth = inject(AuthStore); private readonly fb = inject(FormBuilder);
  protected readonly form = this.fb.nonNullable.group({ fullName: ['', Validators.required], email: [{ value: '', disabled: true }, [Validators.required, Validators.email]], phoneNumber: ['', [Validators.required, Validators.pattern(/^\\+?[0-9 ()-]{9,}$/)]], identificationId: ['', Validators.required], department: [''], primaryRole: [{ value: '', disabled: true }], bio: ['', Validators.maxLength(500)], githubUrl: ['', Validators.pattern(/^https?:\/\//)] });
  constructor() { const user = this.auth.user(); if (user) this.form.patchValue({ ...user, primaryRole: user.role === Role.ADMIN ? 'Administrator' : 'Innovator' }); }
  protected invalid(field: string): boolean { const control = this.form.controls[field as keyof typeof this.form.controls]; return control.invalid && (control.dirty || control.touched); }
  protected initials(): string { return (this.form.controls.fullName.value || 'JH').split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase(); }
  protected cancel(): void { this.form.reset(this.form.getRawValue()); this.profile.clearMessage(); }
  protected save(): void { this.form.markAllAsTouched(); if (this.form.invalid) return; const current = this.auth.user(); if (!current) return; this.profile.beginSave(); this.profile.save({ ...current, fullName: this.form.controls.fullName.value, phoneNumber: this.form.controls.phoneNumber.value, identificationId: this.form.controls.identificationId.value, department: this.form.controls.department.value || '', bio: this.form.controls.bio.value || undefined, githubUrl: this.form.controls.githubUrl.value || undefined }, user => this.auth.updateUser(user)); }
  protected upload(event: Event): void { const file = (event.target as HTMLInputElement).files?.[0]; if (file && file.size > 5_000_000) this.profile.fail('Profile images must be smaller than 5MB.'); }
}
