export enum Role { INNOVATOR = 'INNOVATOR', ADMIN = 'ADMIN' }
export enum AssetCategory { COMPUTING_PERIPHERALS = 'COMPUTING_PERIPHERALS', NETWORKING_INFRASTRUCTURE = 'NETWORKING_INFRASTRUCTURE', IOT_PROTOTYPING = 'IOT_PROTOTYPING', AV_PRESENTATION = 'AV_PRESENTATION', OFFICE_SUPPLIES = 'OFFICE_SUPPLIES', FURNITURE = 'FURNITURE' }
export enum RequestStatus { PENDING = 'PENDING', APPROVED = 'APPROVED', REJECTED = 'REJECTED', CHECKED_OUT = 'CHECKED_OUT', RETURNED = 'RETURNED', OVERDUE = 'OVERDUE' }
export interface User { id: string; fullName: string; email: string; phoneNumber: string; identificationId: string; department: string; bio?: string; githubUrl?: string; avatarUrl?: string; role: Role; createdAt: string; updatedAt: string; }
export interface Asset { id: string; assetTag: string; name: string; category: AssetCategory; description: string; price: number | string; totalQuantity: number; availableQty: number; imageUrl?: string | null; imagePublicId?: string | null; specifications: Record<string, string>; createdAt: string; updatedAt: string; }
export interface TeamMember { id?: string; fullName: string; email: string; phoneNumber: string; studentOrIdNo: string; roleInProject: string; requestId?: string; name?: string; role?: string; }
export interface RequestItem { id?: string; quantity: number; requestId?: string; assetId: string; asset: Asset; }
export interface AssetRequest { id: string; projectName: string; projectAbstract: string; loanDays: number; status: RequestStatus; rejectionReason?: string; startDate: string; expectedReturn?: string; actualReturn?: string; innovatorId: string; innovator?: Pick<User, 'id' | 'fullName' | 'email' | 'phoneNumber' | 'identificationId' | 'department' | 'role'>; teamMembers: TeamMember[]; requestItems: RequestItem[]; createdAt: string; updatedAt: string; }
export interface AuditLog { id: string; action: string; entityType: string; entityId: string; metadata?: Record<string, unknown> | null; createdAt: string; actor?: Pick<User, 'id' | 'fullName' | 'email'> | null; }
