import { AssetCategory, RequestStatus } from '@prisma/client';
import { z } from 'zod';
export const registerSchema = z.object({ fullName: z.string().trim().min(2), email: z.string().email().transform(value => value.toLowerCase()), password: z.string().min(8), phoneNumber: z.string().trim().min(9), identificationId: z.string().trim().min(1), department: z.string().trim().optional() });
export const loginSchema = z.object({ email: z.string().email().transform(value => value.toLowerCase()), password: z.string().min(1) });
export const assetSchema = z.object({ assetTag: z.string().trim().min(1), name: z.string().trim().min(1), category: z.nativeEnum(AssetCategory), description: z.string().trim().min(1), price: z.number().finite().min(0), totalQuantity: z.number().int().min(1), availableQty: z.number().int().min(0), imageUrl: z.string().url().optional().nullable(), specifications: z.record(z.string(), z.string()).default({}) }).refine(value => value.availableQty <= value.totalQuantity, { message: 'availableQty cannot exceed totalQuantity', path: ['availableQty'] });
export const requestSchema = z.object({ projectName: z.string().trim().min(1), projectAbstract: z.string().trim().min(1), loanDays: z.number().int().positive(), startDate: z.coerce.date(), items: z.array(z.object({ assetId: z.string().uuid(), quantity: z.number().int().positive() })).min(1), teamMembers: z.array(z.object({ fullName: z.string().trim().min(2), email: z.string().email(), phoneNumber: z.string().trim().min(9), studentOrIdNo: z.string().trim().min(1), roleInProject: z.string().trim().min(1) })).default([]) });
export const rejectSchema = z.object({ rejectionReason: z.string().trim().min(1) });
export const statusQuery = z.object({ status: z.nativeEnum(RequestStatus).optional(), page: z.coerce.number().int().positive().default(1), limit: z.coerce.number().int().min(1).max(100).default(20) });
export const adminRequestQuery = statusQuery.extend({ search: z.string().trim().max(100).optional() });
